### ISSUE TITLE
Fleet Commander with SSSD: Having to specify a host or hostgroup to get profiles apply to an user

### ISSUE THREAD

**Issue by fidencio** [abbra/freeipa-desktop-profile#3]
This issue is a copy and paste from https://pagure.io/SSSD/sssd/issue/3449

Right now, in Fleet Commander, we can create a profile and assign that profile to a single user. That profile should be assigned to that user whatever the host he logs in.

Right now, the way FreeIPA and SSSD works is that profile is not being applied unles you specify a valid host for the profile. We have worked that around creating a group with all hosts in it and an automember rule for adding all new hosts to that group. Then fleet commander handles it under the hood so the user does not have to specify any host/hostgroup to get that behavior.

After me and @aruiz were talking with @abbra and @fidencio they explained the way SSSD works is to not retrieve anything not related to the host it is running, and @abbra suggested some kind of ACL development to allow the behavior we exposed.

So this bug is mainly to discuss the options for getting that behavior and ask for the implementation.

**Comment by aruiz** [comment]
Thanks a lot for keeping track of this. Lemme know how we can help.

**Comment by abbra** [comment]
I think we have all the support for host categories in both the plugin and SSSD, what's missing is an access control at 389-ds side to allow reading json profile data referenced by a rule with hostcategory=all. I think we should be allowing reading that data because if it applies to all hosts, we basically are giving it away, so limiting access to authenticated users in LDAP is enough. I'll see how to design this rule.

**Comment by abbra** [comment]
Ok, commit 194ca4410ffcdcafa3f870ff4513649e273649ea should solve this issue. You'd need to wipe all entries under `cn=desktop-profile,$SUFFIX` first (ldapdelete one by one) or do a new install because I had to change how CoS template is defined. With the change, it is now possible to define rules which include `--hostcat=all` or `--usercat=all`. These rules will be accessible for all authenticated users/principals in LDAP.

**Comment by abbra** [comment]
Please test and let me know if it works for you. I'll keep this issue open until you'd confirm.

**Comment by abbra** [comment]
Closing.
